### ISSUE TITLE
Cyan ellipsoid drawn to visualize EllipsoidJoint doesn't move when the model moves

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1178]
### Steps to reproduce
- add a body to the arm26 model and attach it to the "r_ulna_radius_hand" body via an EllipsoidJoint (see .osim file here: [arm26_withEllipsoidJoint.txt](https://github.com/opensim-org/opensim-gui/files/4295775/arm26_withEllipsoidJoint.txt))
- open the model in the GUI
- flex the elbow

### Expected result
Cyan ellipsoid remains fixed to arm.

### Actual result
When model is opened | After flexing elbow
--- | ---
![image-when-model-is-opened](https://user-images.githubusercontent.com/4203505/76037418-edb0e800-5f14-11ea-9444-56bfbe1ac5cf.png) | ![image-after-flexing-elbow](https://user-images.githubusercontent.com/4203505/76037421-f3a6c900-5f14-11ea-8728-2f219a1dec63.png)

### Environment and GUI version
Windows 10, OpenSim 4.0 (also broken in 4.1)

**Comment by jenhicks** [comment]
@aymanhab Can you look at this issue?

**Comment by aymanhab** [comment]
Very likely issue is that generateDecoration methods for EllipsoidJoint mishandles the "fixed" flag, leading to the visuals not being updated with the coordinate/state changes.  Testing a fix.

**Comment by aymanhab** [comment]
@tkuchida or @carmichaelong if you can verify the fix in latest build this can be closed. Thank you

**Comment by carmichaelong** [comment]
Looks like the code upgrade fixed moving with the model, but it seems to introduce an issue with the location of the additional body. Using the model provided above, the initial placement of the sphere is different between 4.1 and the latest GUI version (see below):

OpenSim 4.1:
![image](https://user-images.githubusercontent.com/7455790/95611191-56fe5980-0a16-11eb-9a52-41763318640b.png)

OpenSim 4.2-2020-09-02-8bd2ec0 (retrieved 2020-10-08 nightly build):
![image](https://user-images.githubusercontent.com/7455790/95611299-801eea00-0a16-11eb-8e71-2ef2e564ac8e.png)

It seems like the translation for the physical offset frame isn't being respected for the additional body:
![image](https://user-images.githubusercontent.com/7455790/95613223-777be300-0a19-11eb-95c0-99e48cdcb759.png)
Changing the `<translation>` property doesn't seem to affect the location of the sphere, so it seems like this isn't being respected?

As a note for further testing: this shift of the sphere up to the elbow was a little confusing for testing at first because in OpenSim 4.2-2020-09-02-8bd2ec0, the sphere is misplaced to the elbow joint, so changing elbow flexion does not move the sphere. However, changing the shoulder elevation does change the sphere location as expected.

**Comment by aymanhab** [comment]
A note for further testing, it is artificially made harder to troubleshoot an Ellipsoid that has equal radii since it looks like a sphere that is invariant under rotations 💀 I changed the radii to .1 .2 .3 to keep sanity and recommend testers do the same.

**Comment by tkuchida** [comment]
Sorry @aymanhab. The issue is that the ellipsoid doesn't move. This occurs regardless of the radii.

**Comment by aymanhab** [comment]
No worries @tkuchida I just had an issue where I couldn't distinguish the axes so I thought I document it for testing purposes but I agree the issue occurs regardless of radii 😃

**Comment by carmichaelong** [comment]
@aymanhab Fixes look good for ellipsoidal joint (OpenSim 4.2-2020-09-02-8bd2ec0 downloaded on 2020-10-15)
![image](https://user-images.githubusercontent.com/7455790/96162415-5dd11480-0ecd-11eb-9b57-ed3010a73551.png)

**Comment by aymanhab** [comment]
@jenhicks This can be moved to Done. Thanks for testing @carmichaelong
