### ISSUE TITLE
TypeError at "ModelbuildingFunctions.py" file

### ISSUE THREAD

**Issue by dasmehdix** [opensim-org/opensim-gui#1179]
Hi, I was trying to debug the codes with scriptshell windows from [this](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+the+GUI#ScriptingintheGUI-AvailableExampleScripts) guide.I wanted to use "ModelBuildingFunctions.py" file, I changed the comment line like below, but an error occurs. 

**The part of uncommented lines:**

`modelCopy = getCurrentModel().clone()`

`ball = addBodyToModel(modelCopy, 'ball')`

`#sphere =modeling.Sphere(0.2)`

`#attachGeometryWithOffset(modelCopy, sphere)`

`handle = connectBodyWithJoint(modelCopy, ball, 'handle', 'SliderJoint')`

`loadModel(modelCopy)`

**The Error in scriptshellwindow**
`Traceback (most recent call last):
  File "C:/Users/Eriklab2/Documents/OpenSim/4.1/Code/GUI/ModelBuildingFunctions.py", line 162, in <module>
    handle = connectBodyWithJoint(modelCopy, ball, 'handle', 'SliderJoint')
TypeError: connectBodyWithJoint() takes exactly 5 arguments (4 given)`

As far as I understand, I have to add childframe argument, but how can I add it? I am using opensim 4.1 on windows 10 OS.I am using "gait2392 model".

**Comment by aymanhab** [comment]
@carmichaelong Can you reproduce?

**Comment by aymanhab** [comment]
add the lines 
pelvis = modelCopy.get_BodySet().get('pelvis')
handle = connectBodyWithJoint(modelCopy, pelvis, ball, 'handle', 'SliderJoint')

**Comment by carmichaelong** [comment]
@aymanhab Thanks, I was just looking at this too. To be clear, what's being added in the code above is that you're adding a "parent frame", and the ball is the child frame. Typically for these models, when you add a new body, you add the new body as a child frame and then provide the parent frame to which it's connected.

Separately, there's another issue that needs to be fixed with `ModelBuildingFunctions.py`. Currently the attach geometry line in the file provided is:
`attachGeometryWithOffset(newBody, sphere)`
But `newBody` isn't a variable. Should be `ball` instead.

**Comment by aymanhab** [comment]
Thanks @carmichaelong Agreed on both, but since editing same file you can make one PR to address both issues with this out of date script

**Comment by aymanhab** [comment]
Thanks for pointing this out @tkuchida otherwise looks good. Thanks @carmichaelong

**Comment by dasmehdix** [comment]
The issue fixed, much thanks to @aymanhab @carmichaelong 😍
