### ISSUE TITLE
Provide access to IMU-Based IK in the GUI

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#1188]
@jenhicks commented on [Thu Apr 09 2020](https://github.com/opensim-org/opensim-core/issues/2720)

**Comment by aymanhab** [comment]
Here's a mock UI for IMU based IK. Main issues to address/discuss:

1. Whether have separate Calibration Tool (opens door for custom algorithms/options) or fold into IK, or make optional.
2. What options to expose: Example weights? Error Reporting?
![CaptureIMU_IKv1](https://user-images.githubusercontent.com/3972208/92286187-25e0b580-eebb-11ea-8d00-915cbb9b6978.JPG)

**Comment by aymanhab** [comment]
Thoughts? @jenhicks @carmichaelong @nickbianco

**Comment by carmichaelong** [comment]
Thanks for mocking this up. Some responses below:
1. Seems like a separate calibration tool would be good (though even just a separate "Calibration" section even if it's on the same tab could be good)? I don't feel strongly about this until I see some other users work with it.
2. Error reporting would be good. A similar weighting menu to markers would be good so that current users would find it intuitive.

A few additional notes:
- `Rotations from IMU world...`: Are these in degrees? What's the order of rotations?
- `Label in Calibration file` is a little unclear. This is the body that is used for determining the model's "forward" direction, correct?
- `Heading Axis`: Is this the axis from the calibration file or the model's body?
- Is this assuming that "x" will always be the forward direction for the model's body to be aligned?

**Comment by nickbianco** [comment]
Does the calibration step only need to happen once before running several IK trials? If so, then being separate might make sense for most workflows..

**Comment by aymanhab** [comment]
Thanks for the great feedback. 
I draw the parallel to MarkerPlacer use in scaling which is used once or is optional but is shown on same dialog. To have separate dialogs and hope users specify same transform is error prone. Definitely need popup help to clarify usage.  Hoping to minimize custom ui for weights without sacrificing convenience.

**Comment by aymanhab** [comment]
@aseth1 This is the starting point for the IMU based IK user interface. I look forward to your feedback.

**Comment by jenhicks** [comment]
Thanks for the update @aymanhab . I agree with @carmichaelong 's comments.

You might add some more text in the interface to separate the different parts of the process. For example:
(1) Transform data from IMU world frame to OpenSim's reference frame

(2) Place IMU sensors on the OpenSim model
File with orientations of the IMUs while the subject is in the OpenSim model's default pose:
etc.
(Side note: isn't heading correction optional ... the current layout doesn't seem to allow this)

(3) Perform Inverse Kinematics

Yes, let's include weightings. And yes, to error reporting. I think we will suggest the use of these in our paper, so we should expose for others.

I think it would be more robust long-term if alternate calibration approaches were possible. This might be easier or more intuitive if in a separate tab.

**Comment by aymanhab** [comment]
![CaptureIMU_IKv2](https://user-images.githubusercontent.com/3972208/94178292-c2a9c980-fe4f-11ea-9149-b35d24369ab5.JPG)
![CaptureIMU_IKWeights](https://user-images.githubusercontent.com/3972208/94178781-67c4a200-fe50-11ea-9531-81b243624b15.JPG)

**Comment by carmichaelong** [comment]
> The new IK Tool has an Output directory and separate output file, would that be better from a user's perspective?

Maybe to help me understand the user experience better: what are the possible output files from this tool? Seems like if there are a lot of files, could be good just to have a single output directory?

> Users have no indication what weights are set without pushing the weights button, we should indicate if default.

That's a good point. I feel like the `Weights...` button is clear enough for users to hit that I don't think it's necessary to indicate default or not, but I'm open to discussion on this.

> Any other thoughts or comments on layout/text are welcome.

Is this a separate dialog box that can pop up with the previous one that you showed? If not, where does the user specify the base IMU and the base IMU heading?

**Comment by aymanhab** [comment]
As of now there are 2 files .mot output and errors but potentially more for debugging

**Comment by aymanhab** [comment]
![CaptureIMU_IKvcal](https://user-images.githubusercontent.com/3972208/95260059-f506df80-07dc-11eb-8c9a-8d368395e86b.JPG)

**Comment by aymanhab** [comment]
![CaptureIMU_IKimu](https://user-images.githubusercontent.com/3972208/95260261-47480080-07dd-11eb-850f-582a6450a680.JPG)

**Comment by jenhicks** [comment]
Thanks @aymanhab . I think there are ways we could tweak the words, but that is an easy fix. 

As far as the data transformation, should this be the same as in calibration? And can you remind me of the rationale for having people do this in both places?

In the IK step, we should also note prominently somewhere that we assume the IMUs have already been placed on the model (and any other assumptions).

**Comment by aymanhab** [comment]
Thanks for the feedback, happy to tweak the wording.
Same transformation should be applied in both calibration and IK since CoordinateSystem for IMU is different from OpenSim so the transformation has to be applied to both Calibration and IK orientations (I suggested long time ago to use a model in IMU CS but we decided against it). The issue is not critical for IK since it can solve for the transform (model will have strange orientation) but users can see and fix easily.

**Comment by jenhicks** [comment]
I didn't run into any errors this time ... I used the files provided with the distribution (Rajagopal_OpenSense).

Some additional comments/questions:

- On launch I get the error "Can't open file 'opensim.log' for writing. Log file will not be created. Check that you have write permissions to the specified path." Is this expected? If not, should probably be a separate issue.
- Should we use _OpenSense for the folder and model name? Or would _IMU be more general? OpenSense could be fine as it is.

IMU Placer:
- It's not clear what data is being transformed from the way the tool is set-up. Can we put the entry of the orientation file at the top of the tool so this is more clear? Can we change the name to something like "IMU Orientation Data Transformation". In any case the way they second box is labeled, it makes it sounds like everything in the box is option, which I don't think is the case.
- The tool tips still talk about "calibration" instead of "placement". The xml properties also use calibration instead of placement. 
- The model that results from the IMU_placer step is called _calibrated.

IK Tool 
- I have the same comment about the data transformation and the order of the items specified.

- Should we remove the marker set from the model?

**Comment by carmichaelong** [comment]
One other point to add to those above:
IMU IK Tool:
- How do user-selected weights get saved out to file? I didn't see them when saving out the setup file.

**Comment by aymanhab** [comment]
> I didn't run into any errors this time ... I used the files provided with the distribution (Rajagopal_OpenSense).
> 
> Some additional comments/questions:
> 
> * On launch I get the error "Can't open file 'opensim.log' for writing. Log file will not be created. Check that you have write permissions to the specified path." Is this expected? If not, should probably be a separate issue.
This is unexpected and would be due to trying to install the application in a "System" folder that you don't have permission to write to. Did you install for yourself or all-users? Please open a separate issue.

> * Should we use _OpenSense for the folder and model name? Or would _IMU be more general? OpenSense could be fine as it is.
> 
I prefer OpenSense for branding/highlighting OpenSense and also I think the generic OpenSense is more general than IMUs as we may fuse other sensors, but can change if there's a strong case against it.

> IMU Placer:
> 
> * It's not clear what data is being transformed from the way the tool is set-up. Can we put the entry of the orientation file at the top of the tool so this is more clear? Can we change the name to something like "IMU Orientation Data Transformation". In any case the way they second box is labeled, it makes it sounds like everything in the box is option, which I don't think is the case.
I agree that the data selection box should move out of the (Optional panel), I'll see if "IMU Orientation Data Transformation" would fit or be too long. The change will need to be replicated in the IMU IK dialog as well so users are not surprised by a different looking panel/wording/spec.
> * The tool tips still talk about "calibration" instead of "placement". The xml properties also use calibration instead of placement.
This is a bit more complicated because when we wrote the tool, calibration was baked into properties and comments, then we decided to change to "placement" as a more specific form of calibration, this may not be possible to eliminate completely but we can make the comments clearer (e.g. the API has a get_calibrated_model method)
> * The model that results from the IMU_placer step is called _calibrated.
Per the previous item, that may be ok, as using _placed instead of _calibrated may not be helpful
> 
> IK Tool
> 
> * I have the same comment about the data transformation and the order of the items specified.
> * Should we remove the marker set from the model?
I agree we should remove the markers and slim down the model as much as possible.

**Comment by jenhicks** [comment]
I will file a separate issue about the permissions part.

Thanks for the follow-up. Sounds good to stick with OpenSense. We should be sure to mention OpenSense in the documentation, as well. 

What kind of clarifications did you have in mind for the calibration vs. placement?

**Comment by aymanhab** [comment]
I'd leave the xml property as is, just change the wording of the comment from "Name/path to a .sto file of sensor frame orientations as quaternions to be used for calibration." to "Name/path to a .sto file of sensor frame orientations as quaternions to be used for placing IMUs on the model."

**Comment by jenhicks** [comment]
Got it ... sounds reasonable.

**Comment by aymanhab** [comment]
If you can review the wording in the last build, we can close this one @jenhicks

**Comment by jenhicks** [comment]
The updated wording looks good to me ... closing this one. Thanks @aymanhab
