### ISSUE TITLE
NetBeans related error - at Linux build step "make CopyOpenSimCore"

### ISSUE THREAD

**Issue by Linardos** [opensim-org/opensim-gui#1198]
I am following the Linux (beta) instructions step by step but was presented with the following error at step ""make CopyOpenSimCore"". 

![image](https://user-images.githubusercontent.com/26694607/81963209-763abb80-961d-11ea-9a3e-fac1f1c7a902.png)

The error message is not really clear to me
"Check that nbplatform.default.netbeans.dest.dir and nbplatform.default.harness.dir are defined. 
On a developer machine these are normally defined in ${user.properties.file}=${netbeans.user}/build.properties 
but for automated builds you should pass these properties to Ant explicitly."
I don't really know where I should define these variables and to what. 

I am on an Ubuntu 16.04 machine

**Comment by aymanhab** [comment]
You may find the discussion here https://github.com/opensim-org/opensim-gui/pull/1181#issuecomment-628734989 useful, keep in mind though that they use Ubuntu 18 AFAIK.

**Comment by marnunez** [comment]
Hi! Try ` /home/mondestrasz/netbeans-8.2` instead of `~/netbeans-8.2` in the cmake arguments

**Comment by Linardos** [comment]
Hey thanks Marcos, that actually worked. I am now on another issue but I think it pertains to the opensim-visualizer cloning that you already mentioned in the #1181 thread. We can close this one.

**Comment by aymanhab** [comment]
@marnunez and @halleysfifthinc considering the nice work you've done on building the GUI on Ubuntu and the recent surge in interest in running OpenSim (GUI, Bindings) on Linux, would you be willing to upload a package to our https://github.com/opensim-org/opensim-gui/releases page so that other users don't need to redo the same exercise? Or you can share the installer with us and we post it to simtk.org as a Beta. If interested we can work out the logistics by email. Thank you
