### ISSUE TITLE
When navigating to open a Model file, "Recent Items" takes awhile to load

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1230]
### Steps to reproduce
1. File --> Open Model...
2. Hit Recent Items (Windows)
3. Loads eventually, but takes awhile

Looks to be slow on OpenSim 4.2-2020-09-02-8bd2ec0 (master) and OpenSim 4.2-2020-10-23-c635110 (threejs update) branches. OpenSim 4.1 distribution is not slow

**Comment by jenhicks** [comment]
This doesn't seem slow for me, but would be good to have you test @carmichaelong

**Comment by carmichaelong** [comment]
Tested with OpenSim 4.2-2021-01-09-fc62aad, and comparing with OpenSim 4.1, the current build is still slower than OpenSim 4.1 That being said, IIRC when I wrote this issue, the problem was much much worse. It's much better now even if there's still a little delay to the point where this could get closed.

@aymanhab Have you seen this before or could this be specific to my machine?

**Comment by aymanhab** [comment]
Thanks for checking @carmichaelong I think this is specific to your machine since the whole cache of recent files is maintained by the underlying netbeans platform in some files/cache. This folder is typically cleared with a new install but the details are mostly hidden and if issues exist they's be machine specific.
