### ISSUE TITLE
Names of "Preview" functions in the GUI

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#1259]
We now have a "Preview Experimental Data ..." and "Preview Sensor Data ..."

It is not super clear what these two options do.

Perhaps:
Preview Sensor Data -> Preview Orientation Data (as I believe this is what it does)
and
Preview Experimental Data .." -> Preview Marker and GRF Data (or what would be appropriate?

@carmichaelong @aymanhab Thoughts?

**Comment by aymanhab** [comment]
@jenhicks I would not change the name of the old button as it will confuse users who are not using IMUs unnecessarily. The mental picture for these users have already been drawn,  documentation/forum posts that date years back has reference to this name so i wouldn't touch it.
For the new one, I'm open to changing to clearer name, the reason I stuck with Sensor rather than orientation is to support showing gravity vector or other data in the future without having to change the menu pick name but I'm open to other arguments.
