### ISSUE TITLE
Updating IMU's Translation and Rotation properties don't update until model is saved and loaded again

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1340]
@aymanhab 

### Steps to reproduce
1. Run IMU placer step on OpenSense example
2. Change properties for Translation and Rotation for one of the IMUs (e.g., `femur_r_imu`)
3. Note that the GUI does not update
4. Save the model
5. Load the model
6. GUI shows updated IMU location

Checking some other components, did not find other components that had the same behavior. e.g., muscle path updates, wrapping surface location, and even updating PhysicalOffsetFrame's within a Joint showed the current update immediately in the GUI

### Environment and GUI version
macOS 12.3.1. OpenSim 4.4-2022-04-11-e3e3d1d

**Comment by aymanhab** [comment]
Thanks for reporting @carmichaelong This boils down to the fact that the IMU is "connected" to the Frame rather than a child of it. The axes for example update instantly as expected. Can you verify please?
Will investigate how to collect components that are connected to a Frame or some other surgical workaround.

**Comment by carmichaelong** [comment]
Yes, confirmed that the axes update instantly.
