### ISSUE TITLE
Missed some XML properties in IK setup files

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1342]
### Steps to reproduce
1. In GUI, Tools>Inverse Kinematics
2. Adjust and save the setup file

### Actual result
The following XML properties are missed in the saved file:
<results_directory>
<model_file>
<report_errors>

### Environment and GUI version
v. 4.3

**Comment by aymanhab** [comment]
We intentionally do not include the model_file since when you run in the GUI you're running on the current model which may or may not have been saved to a file (e.g. post scaling). Some other properties are not exposed to the GUI for simplification but can be edited in the XML file directly (e.g. report_errors), others computed based on input (results_directory is deduced from output_file) to reduce clutter.

**Comment by mrrezaie** [comment]
As a user, I prefer to have these properties in XML file. Because I usually run the tools from opensim-cmd and It fails when <results_directory> and <model_file> do not exist. Then, I have to add them manually. Also, other tools already have these properties, so it wouldn't be clutter.
