### ISSUE TITLE
opensim could not associate motion to current model

### ISSUE THREAD

**Issue by Francesca-Oppia** [opensim-org/opensim-gui#1384]
Hello everybody! I'm having some troubles with OpenSim. I am using a model .osim for my thesis and converted the .c3d files in .mot and .trc , now I should be able to associate these last .mot files with the model , but te output is always "Opensim could not associate motion to current model". 
I've verified the original model from Opensim and there's no such problem. 
Can anybody help? Any tips would be helpful! I'm getting mad

**Comment by aymanhab** [comment]
@Francesca-Oppia No reason to get mad. This doesn't belong here but to the user forum here https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
In order to associate a motion to a model the file should contains values for coordinates, we'll clarify the message but you could have got the same answer way faster on the user forum

**Comment by aymanhab** [comment]
Issue #1386 opened to clarify the message.
