### ISSUE TITLE
check behavior of integrator settings panel in 4.0

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#230]
To work around issue #153, a line that could be updating the integrator settings panel in CMC, RRA was commented out. Seems hard to test when most files we have use defaults. This is a place holder to check the behavior vs. 3.3

**Comment by jenhicks** [comment]
Check that integrator settings behave correctly.

**Comment by jenhicks** [comment]
@aymanhab could you provide more details about what we should test

**Comment by aymanhab** [comment]
The call that was removed was to "use time steps from states file", the checkbox is unused except in ForwardTool. We need to make sure this continues to function properly in ForwardTool  (if we have test data/files)

**Comment by jimmyDunne** [comment]
Im not entirely sure what the expected behavior is here- when the 'Use time steps from states file' is checked, what is supposed to happen?

There is no input states file for FWDTool; there is an initial states file, is that what is meant? My first thought is that I should be able to input a full states file and get the exact time steps from the file- so the time steps seen in the output states file from FWDTool, should match exactly the time steps from some (arbitrary) input states file. 

If so that is not what is currently occurring. I specify a states file that I generated with a constant step size in the 'Initial State' dialogue box; 

![constant_step_sto](https://user-images.githubusercontent.com/5296507/38947822-c08b3fa0-42f2-11e8-87ab-212f3e5889f1.png)

I check the box for  "use time steps from states file".  When I run the tool, I get a strange result and with the output state looking like this;

![input_step_sto](https://user-images.githubusercontent.com/5296507/38947913-0767c628-42f3-11e8-8bf8-127bd19bdca4.png)

Like I mentioned above, I would expect that the output state would have the exact time steps as the input state, which isn't happening here.

Let me know if that is not the correct use case and we can drill down on the changes that need to be made for the test. Thanks!

**Comment by aymanhab** [comment]
@jimmyDunne I'd say the main reference/documentation is what happens in 3.3 since the behavior is undocumented elsewhere and this is rarely used functionality AFAIK.

**Comment by jimmyDunne** [comment]
I tested the files in 3.3 and got completely erroneous results (the model starts below the floor and shoots upward) 

![integrator_33.gif](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/8ff993c2-b9a4-4664-8714-1b360eaa4b09)

The functionality is broken in 3.3 as well as in 4.0 so we have an opportunity to define the behavior now :)

A few candidate solutions;
(1) We get rid of the checkbox all together since it is not clear what the feature even is.
(2) We keep "Use time steps from states file", and when someone checks the box the output file step sizes must match the input step sizes from the file. 
(3) We keep "Use time steps from states file", rename it to "Use initial time step from initial states file", and set the step size to a constant rate from the initial states file.

**Comment by aseth1** [comment]
If it is rarely used, undocumented and the expected behavior is not well-known, I vote to remove it.

An improvement would be an option to use a fixed reporting interval, which we could pass to underlying reporters. This could be a feature for 4.1.

**Comment by aymanhab** [comment]
Removed in PR #702

**Comment by jenhicks** [comment]
@aymanhab Could you explain what needs to be tested for this one?

**Comment by aseth1** [comment]
Verified using forward simulations of the ToyDropLanding model.

1. the option to "Use time steps from states file" has been removed.
2. some integrator settings have the expected effects:
   - setting max and min step size results in fixed-time step integration
   - tightening the accuracy increases the number of integration steps
3. The "Maximum number of steps" setting appears to have no effect (also in 3.3). Opened [core #2228](https://github.com/opensim-org/opensim-core/issues/2228) to track.

**Comment by jenhicks** [comment]
@aseth1 I will mark this one as verified on windows and mac since you opened the additional issue.
