### ISSUE TITLE
GUI uses lots of system resources, causes fan to turn on

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#265]
Reported by me, @jenhicks, and @aseth1 . The GUI, on macs, causes the fan to turn on pretty loud. Not sure why. It could be the 1GB heap size setting in opensim.conf.

**Comment by tkuchida** [comment]
I left OpenSim open in the background for a few minutes and at some point OpenSim64.exe ate up a CPU core:

![](https://user-images.githubusercontent.com/4203505/40110403-c0553fae-58b4-11e8-99f9-fa019bf7843d.png)

Anyone else encounter a similar issue? AppVeyor artifact OpenSim-d8bfa962-2018-05-09-win64.exe

**Comment by aseth1** [comment]
I am seeing similar issues on Mac. I started noticing my fan turn on since the versions we cranked out to create the image for the 4.0 paper.  On the latest Mac version I get a lot of fluctuation during playback (gait2392 CMC results) but CPU remains relatively high for just playback and my fan turns on.  You can see that OpenSim + JXBrowser exceed 100% (100% on Mac is a single core).
<img width="815" alt="screen shot 2018-05-16 at 11 04 26 am" src="https://user-images.githubusercontent.com/6494122/40135178-7ccbc100-58f9-11e8-94af-0957f867b870.png">
<img width="815" alt="screen shot 2018-05-16 at 11 04 53 am" src="https://user-images.githubusercontent.com/6494122/40135501-5de51fec-58fa-11e8-913c-19ae7a16d45a.png">
