### ISSUE TITLE
Syncing the motion of two models plays back poorly

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#333]
With latest ISB release on Windows:
- loaded two jumper models
- loaded ik motion file associated with each model
- synced motions, which results in very slow and choppy playback
- making only one current plays normally

**Comment by aymanhab** [comment]
Caching uuids to speed lookup doens't do more than 10-15% improvement in performance. This is a Visualization or Performance issue rather than Animation (per the label) since the correct data is sent it's just that rendering is slow with multiple models. Creating two scenes one for current model, the other for all others/background may do the trick. Will address with Visualization.

**Comment by jenhicks** [comment]
Choppy on my macbook pro. Could try having each model be its own scene.

**Comment by jenhicks** [comment]
Syncing motions is working well for me on my mac.
I tried:
jumper, IK + CMC results
gait2354, IK + CMC results

I tried .5x, 1x, 1.2x playback speeds and all worked well. hooray!

**Comment by aseth1** [comment]
The Jumpers keep jumping (smoothly).  
![opensim_video](https://user-images.githubusercontent.com/6494122/43110277-e40e0464-8e9f-11e8-89e0-3c8989dcdae1.gif)

Synched human with EXO with cmc-states and Chimpanzee IK motion with associated SO activations and playback was smooth, as well.

Verified on Windows OpenSim_cea85df3-2018-07-18 (on my desktop)
