### ISSUE TITLE
IK fails to run right after Scaling

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#421]
Reported on Tutorial 3. Loading the Scaled model and running IK succeeds.

**Comment by aseth1** [comment]
According to @bspineda Tutorial is working, so this issue is likely fixed. @jimmyDunne please confirm.

**Comment by aymanhab** [comment]
Both platforms have been verified, closing.

**Comment by jimmyDunne** [comment]
Reopening because this is reoccurring. 

Seen when scaling the Hamner running model followed by performing IK. The motion playback doesn't occur in the visualizer. 

![hamner_running](https://user-images.githubusercontent.com/5296507/38701757-4d3f21d2-3e8e-11e8-88d7-c935b206bcb2.gif)

If I open the scaled model and run IK, the motion playback is as expected.

**Comment by aymanhab** [comment]
@jimmyDunne This issue referred to running the tool rather than animation/playback, if the latter is an issue then open a new one or add a note to #333 as possible duplicate. It's also possible that it is Model specific. Tthe original issue was in Tutorial 3 which you should be able to test separately. Thanks

**Comment by jimmyDunne** [comment]
new issue @ #665
