### ISSUE TITLE
GUI does not find Geometry directory

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#440]
Opened double-pendulum model. Model appears in Navigator and floor is drawn but no model geometry (cylinders and spheres). Fix from @aymanhab was to open Edit->Preferences… and provide the (Windows) path in the "Geometry Path" field.

OpenSim-4.0.Beta_110817_Win64

**Comment by aseth1** [comment]
I had the same experience with latest build: OpenSim 2112110-2018-01-31, when opening /Users/aseth/Documents/OpenSim/4.0.Beta/Models/Gait2392_Simbody/gait2392_simbody.osim

Geometry path is incorrectly set to:
/Users/aseth/Applications/OpenSim 4.0-beta/OpenSim 4.0.app/Contents/Resources/OpenSim/Geometry/

Updating the path fixes the issue.

**Comment by jenhicks** [comment]
This is still an issue for me.

**Comment by aymanhab** [comment]
@jenhicks what platform are you on?

**Comment by jenhicks** [comment]
Windows 10, via virtual machine

**Comment by aymanhab** [comment]
Great, if we fix the issue that every release has its own preferences then this should be fixed then.

**Comment by jenhicks** [comment]
Can fix by prepending geometry for the installation to the front of the geometry path.

**Comment by jenhicks** [comment]
Only do this when you're installing new resources.

**Comment by aymanhab** [comment]
Fixed in PR #689

**Comment by aseth1** [comment]
Hard to know if this issue is fixed. The fact that it finds geometry on the path below is not indicative of a valid solution.

**F:\Users\aseth\Apps\OpenSim3.3x64\Geometry;F:\Users\aseth\Apps\OpenSim-aac4acf4-2018-05-02\opensim\OpenSim\..\\Geometry\;F:\Users\aseth\Apps\OpenSim e07981e0-2018-05-15\OpenSim\..\\Geometry\**

In all likelihood it is finding the Geometry files from 3.3 installation.

If I remove the previous paths to be left with:
**F:\Users\aseth\Apps\OpenSim e07981e0-2018-05-15\OpenSim\..\\Geometry\**

The arm26 model still loads correctly although I cannot paste this path in Windows explorer to navigate to that folder. Perhaps #745 should be resolved before closing this issue.

**Comment by jimmyDunne** [comment]
I installed artifact OpenSim-2888c1c6-2018-05-28-win64.exe on a W10 machine. The geometry path in the preferences folder is below.

C:\Users\Delp Lab\Documents\;C:\OpenSim_Test_Builds\opensim_05122018\opensim\Geometry

The version on the path was one from three versions ago when I last cleaned the Geometry path in preferences, so each installation since has not put the version being installed on the path. A new installation should either overwrite the GeometryPath preference with the new install and notify the user, or it should prepend the new path to the current path.

**Comment by aymanhab** [comment]
@jimmyDunne To force invokation of the pathway that installs resources and possibly update GomettryPath, install a version from last March then install the latest artifact.

**Comment by aymanhab** [comment]
Moving to needs verification, pending testing by @jimmyDunne

**Comment by jenhicks** [comment]
On Windows, change preference to something that doesn't work. Install new version. Force installResources() via GUI scripting shell. Relaunch GUI (or maybe in same session and load new model)

**Comment by aseth1** [comment]
1. Setting the *Geometry Path*  preference to blank causes OpenSim to default to the resources folder:
`F:\Users\aseth\Apps\OpenSim_cea85df3-2018-07-18\OpenSim\..\\Geometry\`

2. *Geometry Path* set to `C:\Windows` should be functionally useless, yet after uninstall and reinstall. I was still able to load model with geometry. Not sure how this is working?
![image](https://user-images.githubusercontent.com/6494122/43109442-b6da2ab2-8e9b-11e8-85a7-c1f7e0817434.png)

3. Not sure forcing of `installResources()` now does anything since the `C:\Windows` path is unchanged and the model still loads.

I think we need a fresh (virtual) machine to test this.

**Comment by jenhicks** [comment]
Since we have the beta posted, I suggest we wait for any feedback from users. @jimmyDunne please let us know if you encounter any issues like this on the forum (for 4.0)

**Comment by jimmyDunne** [comment]
Will do. It seems like we should tell people in the documentation that they have to manually update their Geometry Path in Preferences?

**Comment by jenhicks** [comment]
I don't think people should have to manually edit in most cases, right @aymanhab ?

**Comment by jimmyDunne** [comment]
If you have an existing 3.3 (or any other version) you will have to. I just installed the latest version on a Windows VM which had 3.3 and 2.4— the 4.0 Geometry path got appended. Having these multiple paths obfuscates where Geometry is coming from.

**Comment by aymanhab** [comment]
It is true that the path gets appended (prepended?), generally this has not been an issue when Geometry is consistent but could be an issue if not (e.g. binary vtp picked instead of new ASCII vtp). If the 4.0 appears in front though then I believe we're fine.

**Comment by jimmyDunne** [comment]
There have been changes to Geometry and Models which breaks the continuity between versions. Since the preference is shared between multiple OpenSim versions (If you change the Path preference in 4.0, it will be that path when opening 3.3), I will be manually changing the Geometry each time I switch between versions to make sure I am using the version-specific Geometry folder.

**Comment by tkuchida** [comment]
> I will be manually changing the Geometry each time I switch between versions to make sure I am using the version-specific Geometry folder.

This issue may affect users as well (e.g., if some projects are in 3.3 and others are 4.0). To encourage adoption of 4.0, perhaps we should consider having two entries for geometry path (pre-4.0 and 4.0+)?

**Comment by aymanhab** [comment]
Actually the changes in terms of Geometry file contents is exactly that some binary vtp files from 3.3 are not supported so getting ASCII version from 4.0 is not harmful to 3.3 users. The only reason to edit path manually is if a user has files that share same name as distributed files. We discussed having separate preferences per version but didn't get around to implement it.

**Comment by aseth1** [comment]
In today's meeting we discussed having separate registry key for 4.0 preferences and this would be overwritten with defaults upon installation. This would prevent issues of mangling user's working 3.3 preferences/setup.  Ideally, we would give the user the option to use previous settings, or not to update the preferences if they already exist.
