### ISSUE TITLE
Display pop-up box if an object is automatically renamed when model is opened

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#483]
Jen: Users should get a warning and now what steps to take if we edit their mode files.

If an object was renamed when the model was opened, the user should be notified that additional edits might be necessary in the model file (particularly if the model fails to open). Should report which objects were renamed.

**Comment by aseth1** [comment]
In the API we can change warnings to Exceptions, but GUI will have catch and throw up a dialog with the message. If there are many renames (e.g. dozens to hundreds of PathPoints) this could be very agitating. Would need away to "ignore all". 

Another option, is to add/return a flag that informs us if finalizeFromProperties has changed any property values, and in that case the GUI would show a single pop-up with a message to check the messages console for the list of the components that were renamed.

**Comment by aseth1** [comment]
I also would like us to avoid renaming Components that are unique by name and type if we can. Since we agreed that the pathname must be unique, we can roll the Model Sets into Components (Lists or some other Container) so that you can have: `/hopper/Bodies/foot` and `/hopper/ContactGeometry/foot` (which is pretty typical of 3.3 models) and would be easier than renaming `/hopper/foot` (the Body) and `/hopper/foot_0` (the ContactGeometry) and having to find all the contact Forces that use the `foot` ContactGeometry and rename to `/hopper/foot_0`.

The tradeoff is that the pathnames get longer (minor) but it also forces users to think they need these sets (groupings) of Components in the Model, which the Component interface does not require. We can add subcomponents to any Component. The GUI will need likely need these component Sets for the Navigator for awhile, so perhaps it is fine to use these typed sets to help differentiate components (e.g. include in pathname) since they'll be there for the foreseeable future.

**Comment by jenhicks** [comment]
Add a pop-up to review the messages window.

**Comment by jenhicks** [comment]
@aseth1 Any updates on this one?

**Comment by aseth1** [comment]
@jenhicks There were several proposals made.  Let me summarize:
1. Change warnings into Exceptions so the GUI can notify users of renames. This will require a solution to multiple renames bogging down the user. It may also be somewhat counter-productive to throw an exception when we are doing the rename to make the transition easier for the user by avoiding the non-unique name exception. 
2. have `finalizeFromProperties` return a `bool` if the properties were changed during finalize. This would then apply to Bodies and other Component's whose values are changed. It would then be up to `Model` or the GUI to check the flag throw and/or popup a message for the user. Introducing a return flag is a change to the Component Interface that API users will likely not use or need. It will serve a GUI need.
3. We thwart the renaming in many cases by including the fact that components (particularly in previous models) are organized  by type. Components live in typed Containers (e.g. Sets) and these Containers could be Components.  This would remove issues of renaming a *foot* `Body`  because of a *foot* `ContactGeometry` because now the set name would be part of their Component's pathname (e.g. '/hopper/Bodies/foot'). The downside is that the paths get longer, but users get to keep their naming convention in many more cases. 

Are there any preferences by @tkuchida, @aymanhab, @chrisdembia. @jimmyDunne? A combination of 2 and 3 might be most satisfactory for the user. 1. seems the easiest to hack in place.

**Comment by aymanhab** [comment]
Related
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9262&p=0&start=0&view=&sid=53d8186808ebbf174bc6acfdd9549dcb

**Comment by aseth1** [comment]
In https://github.com/opensim-org/opensim-core/issues/2260 we are discussing locking down the XML format for 4.0. Before we do that we may wish to consider proposal **3.** above, which would eliminate some of headache of Components not being.  uniquely named in older models.

We should still warn/popup when there are duplicates, but we could at least eliminates then need to rename in the majority of cases of upgrading a working <=3.3 model to 4.0.  I would appreciate comments/feedback @tkuchida @aymanhab @chrisdembia.

**Comment by aymanhab** [comment]
Added comment/preference under https://github.com/opensim-org/opensim-core/issues/2260

**Comment by aseth1** [comment]
Translating @aymanhab 's comment here:

> Option 3 or a variation of it seems best to me. One key question, when we do name search for components do we have expected type(s) or base class to search for? If so then we can bake this in the search without even implementing 3 by making the search filtered, and not introducing artificial components that stick forever in all legacy/pre4.0 models

**Comment by aseth1** [comment]
Type uniqueness cannot be guaranteed. If you have a `Socket<Frame>` and you have a `Body` and `OffsetFrame` of the same name, their is a collision. I believe @tkuchida ran into this type of issue so I don't think it is an abstract problem. Especially now that we can have components located anywhere (not required to put them all in Model's sets). It is even more critical that paths be unique. 

I guess I am arguing since we have Sets in Models,  that these Sets really act like sub-directories in a filesystem structure, which our `ComponentPath` emulates. In which case, including the sub-directory name in the path makes sense and then guarantees existing models with components in different sets are  treated as unique and the renaming problem can be avoided in these instances.

**Comment by tkuchida** [comment]
> Sets really act like sub-directories in a filesystem structure, which our ComponentPath emulates. In which case, including the sub-directory name in the path makes sense and then guarantees existing models with components in different sets are treated as unique and the renaming problem can be avoided in these instances.

That sounds reasonable to me. IIRC we discussed having "container" Components that did nothing more than maintain a bunch of children. Creating one such container for each Set (e.g., "ForceSet" -> "ForceContainer") might be a general solution, with the potential to write an algorithm that retains only the containers that are necessary to avoid naming collisions.

**Comment by aymanhab** [comment]
Thanks for explaining @aseth1 While it sounds like we introduced the duplicates in the case of @tkuchida (since pre 4.0 models didn't have offset-frames), it appears that including the sets in the names is a general solution that will work regardless. As you pointed out the testing of old models, tools and GUI will be a massive task. Also how would the tools/setup-files that have body names, marker names etc. handle this change?

Do you think it makes sense to have a separate off-line utility to rename duplicates if the automatic conversion fails, if this is not very common?

**Comment by aseth1** [comment]
To discuss at next planning meeting with @tkuchida and @chrisdembia present

**Comment by jenhicks** [comment]
Plan for this week:
- What is scope of implementation?
- What are downstream effects on tools and GUI?
Then we will reassess on Thursday

**Comment by chrisdembia** [comment]
This should now be under Needs Verifying, correct?
