### ISSUE TITLE
Enable access to all fields of the Scale Tool 

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#6]
Reported at the workshop

**Comment by aymanhab** [comment]
Can you verify @jimmyDunne or @tkuchida that this can be closed. Thanks

**Comment by tkuchida** [comment]
> Can you verify @jimmyDunne or @tkuchida that this can be closed.

I am unable to verify because I cannot find the steps taken that produced the issue. I don't know what I'm looking for. On https://github.com/opensim-org/opensim32/issues/12, there is a comment that says "On windows 7, can't edit the measurement set fields. Need to identify the different set of issues for windows 8" – I did not encounter an issue editing the measurement set fields. The title of this Issue is "Enable access to all fields of the Scale Tool" – I was unable to find a field in the Scale Tool that was incorrectly disabled.

@aymanhab you made a comment above, "I can reproduce the behavior with a model that Matt sent me earlier". If the issue is model-specific, please provide me with the model and I can test editing the measurement set fields on my machine.

AppVeyor artifact OpenSim-6826a797-2018-02-28.zip
Tested using gait2354_simbody.osim with subject01_Setup_Scale.xml

**Comment by jenhicks** [comment]
Seems good to me on Windows 10
