### ISSUE TITLE
"(Deg.)" suffixes in Plotter's "Y-Quantity…" drop-down list are not useful

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#669]
### Steps to reproduce
- load a model
- run a simulation
- open the Plotter
- click "Y-Quantity…"

### Expected result
Items in list match items in "Motions" branch of Navigator

### Actual result
Items in list are suffixed with "(Deg.)". I don't think this suffix is useful here. Presumably, the suffix means that rotational coordinates and speeds will be plotted in units of deg and deg/s, but the "(Deg.)" suffix is appended even if there are no rotational coordinates in the model. Further, the time to inform the user of the units is when they are looking at the plot, not when they are choosing the motion. Units could instead be displayed in a label below the plot. Providing the user with the ability to select/toggle between degrees and radians would also be nice.

![](https://user-images.githubusercontent.com/4203505/38777527-5cd11ca0-405e-11e8-9297-36f598a7da22.png)

### Environment and GUI version
AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip

**Comment by nickbianco** [comment]
I've encountered this issue while testing the "Simulation-Based Design to Prevent Ankle Injuries" lab for this year's ME/BIO485 class. Selected the menu dropdown labeled "Results(Deg.)..." actually loads results in radians; users must load the data from file to plot in degrees. This is relevant to this lab since they compare subtalar angles from their drop-landing simulations to a literature value. I've temporarily updated the lab warning users that the must load from file to get the correct units.

Since this could cause a lot of confusion and seems like a straight-forward fix, I'd propose adding this to the 4.2 release. @aymanhab, @jenhicks, thoughts?

**Comment by aymanhab** [comment]
I agree @nickbianco Will take a look to see the rationale in the GUI code and if we can show it selectively vs. remove altogether.

**Comment by nickbianco** [comment]
I like Tom's suggestion to allow users to select radians vs. degrees. Not sure how difficult that would be though.

**Comment by kernalnet** [comment]
Dear Experts,
It would be great if you let the users save the "_pErr.sto" (both RRA and CMC results) in degrees too.

**Comment by aymanhab** [comment]
As of now, when loading .mot file (Deg.) is always appended to the display name, when loading .sto file (Deg. or Rad.) is appended depending on whether the inDegrees flag is true or false regardless of contents. The plotter is rather low level and has no understanding of rotational/translational coordinates or in most cases if the files are related to a specific model.

**Comment by aymanhab** [comment]
My proposal for fix: 
Short term remove the Deg., Rad. annotation altogether, maybe show a line in the message window if conversion is going to occur.
Long term: Annotate the file with units/labels (as part of Table MetaData) so that there's an interface to get/convert/annotate data when plotting or using data files downstream but this is wider in scope than this specific issue.

**Comment by jenhicks** [comment]
We should at least remove the Deg/Rad annotation if they are correct in some cases. Let's discuss the longer-term fixes, as well.
