### ISSUE TITLE
Change the title in the View Controls dialog to 'Select Scene Light'.

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#789]
### Steps to reproduce
- Expand View Controls, Lighting
- Click on the Scene Light
- Set Scene Light position 
- Try and close Scene Light

### Expected result
There should be an on/off switch for the scene light so that I can close it. 

### Actual result
There is no way of switching off the Scene Light. A GUI restart is required to get rid of it. 

edit: the only way to close the scene light is to randomly click in the visualizer space. This is a poor way of toggling off the scene light triad. 

### Environment and GUI version
W10
OpenSim-543e2ecd-2018-05-27-win64.exe

**Comment by aymanhab** [comment]
what do you mean by "close"? The scene light is always there you just get to move it with the triad and if you pick off the triad, it gets deselected. Can you clarify what is the functionality you're asking for? Thx

**Comment by jimmyDunne** [comment]
It isn't clear that just clicking somewhere in the visualizer will 'deselect' and close the scene light triad- especially when left- or right- click-and-hold to rotate or translate the scene doesn't cause the triad to close. You are now also introducing an issue when Users want the scene light triad visible while they are manipulating the model or scene; the triad will now close whenever a wayward click is made. 

The Scene light triad should have an on/off, view toggle, open/close...whatever you want to call it.... in the View Controls.

**Comment by aymanhab** [comment]
@jimmyDunne The use case for this is to use the button to select the scene light and move it until happy with it then click elsewhere to deselect. This is exactly what you do when selecting Markers or PathPoints to move. It may make sense to change the label on the button to "select Scene Light". 
There can't be an on/off button because it would give the incorrect implication that selection can stay on. If you select something else it will be deselected. There's no way more than one object can be selected in the visualizer.

**Comment by jimmyDunne** [comment]
Then you need to change the title in the View Controls dialog to 'Select Scene Light'.

**Comment by aymanhab** [comment]
Sure, will do. Thanks @jimmyDunne
