### ISSUE TITLE
Model at x=0 cannot be offset to 0.01, 0.02, or 0.03

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#842]
### Steps to reproduce
1. open arm26 model
2. right-click "arm26"; select Display > Model Offset...
3. in first textbox, change "Offset X" from 0 to 0.01
4. click OK
5. right-click "arm26"; select Display > Model Offset...

### Expected result
After step 4, model should move in +X direction. After step 5, dialog box should indicate that model offset is (0.01, 0, 0).

### Actual result
Model does not move after step 4. When Model Offset dialog is opened in step 5, it still reads (0, 0, 0). To move the model from 0 to 0.01, it must first be moved from 0 to x >= 0.04, then moved back to 0.01. Interestingly, when the model is at x=0, it can be moved to -0.01 but not 0.01, 0.02, or 0.03. This bug is very inconvenient when trying to fine-tune the position of a model (e.g., when generating a figure) and takes the user's attention away from the meaningful task.

### Environment and GUI version
AppVeyor artifact OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by aymanhab** [comment]
Thanks for reporting Tom. The slider and textbox combo in general doesn't allow arbitrary numbers, only these corresponding to the slider "ticks". For placing models side by side for comparison or overlaid that was never an issue since 1.0.  But your use case is slightly diffetent. Maybe able to increase ticks for now, eventually will change interface to accomodate.
