### ISSUE TITLE
Edits to Wrap Object Properties in GUI are not visualized 

### ISSUE THREAD

**Issue by clnsmith** [opensim-org/opensim-gui#844]
### Steps to reproduce
Open arm26.osim in 4.0 gui
edit wrap object (TRIlonghh) properties (xyz_body_rotation, translation, quadrant, dimensions)

### Expected result
The wrap object visualization should update in the gui to reflect the change in property value.

### Actual result
The wrap object visualization is unchanged. If the model is saved then reopened, the changes are visualized.  

### Environment and GUI version
APPVeyor GUI version: OpenSim 32ef4769-2018-05-12
Windows 10

**Comment by aymanhab** [comment]
The scope: Edits to geometric attributes of WrapObjects and ContactGeometry are not propagated to visualizer, because analytic geometry types can't be modified post creation. I did something similar to handle Geometry edits so need to propagate that fix. Additionally WrapObjects have "quadrants" and both WrapObjects and ContactGeometry expose an extra Transform rather than use Frames. 
Status: Fix in progress.

**Comment by aymanhab** [comment]
All edits are now propagated to visualizer and are undoable.
