### ISSUE TITLE
Simulating Apoorva's model throws exception related to assembly tolerance

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#86]
When I try to simulate Apoorva's model by clicking the green running dude, the Messages window says the following:

![image](https://cloud.githubusercontent.com/assets/846001/23584572/139e0a90-011a-11e7-9db6-8dec2ef69136.png)

The simulation stops, and there is no red stop sign in the lower right corner, and I am able to continue using the GUI.

Also, the simulation took a long time to start, and it wasn't clear what was happening.

Windows 10; 64-bit GUI build.

**Comment by aymanhab** [comment]
Model free falls as expected running FD from runningdude 🏃‍♀️ as expected

**Comment by jenhicks** [comment]
The model simulates but I get errors:

AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.

The torso geometry is also missing.

**Comment by aymanhab** [comment]
The geometry file that comes with the model is binary vtp, if removed we should find correct one in installation or it can be replaced with ascii vtp in updated download of the model.

**Comment by jenhicks** [comment]
@apoorvar Is the error I note above expected?

**Comment by apoorvar** [comment]
The missing torso geometry has been seen before when using the vtp file from simtk.org. Ayman has an alternate geometry file that we can use instead, I believe (please correct me if I'm wrong).

I don't get the AssemblySolver exception when I run the forward tool using the green running dude in 3.3, but am getting that exception when doing the same thing in 4.0. Is this related to the satisfying constraints for the patella in 4.0?

**Comment by chrisdembia** [comment]
When clicking the green guy in the GUI for the copy of `Rajogopal2015.osim` from the `opensim-models` repo, I get the following warnings:

```
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 1.9271717500892522e-09 required: 1e-10.
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 3.7804579401242677e-09 required: 1e-10.
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 4.3652533727724107e-09 required: 1e-10.
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 5.7781486185106551e-09 required: 1e-10.
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 6.7404181435550607e-09 required: 1e-10.
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 7.3084292924542173e-09 required: 1e-10.
AssemblySolver::track() attempt Failed: SimTK Exception thrown at Assembler.cpp:973:
  Method Assembler::track() failed because:
Unable to achieve required assembly error tolerance.
```

I tried simulating this model with `opensim-core` (no GUI) and did not get any of these messages. The fact that this message is generated repeatedly suggests that the GUI is causing an assembly for each frame for purposes of visualization.

With `opensim-core`, I didn't even get a warning at the beginning of the simulation.

**Comment by aymanhab** [comment]
@chrisdembia Indeed the Model::assemble(state) is called why would that be an issue? The GUI workflow is likely different from what you did in opensim-core. We should discuss in person.

**Comment by chrisdembia** [comment]
Yes, we can discuss in the daily sprint.

**Comment by chrisdembia** [comment]
Here's what I did in `opensim-core`:

```cpp
        Model model("/Users/chris/Desktop/opensim-models-master/Models/RajagopalModel/Rajagopal2015.osim");
        auto state = model.initSystem();
        Manager manager(model, state);
        manager.integrate(1.0);
```

**Comment by chrisdembia** [comment]
@aseth1 located the line of code that calls `Model::assemble()` and causes the warning: https://github.com/opensim-org/opensim-gui/blob/fa6407e08d0979285513842fbf08aca5b58e29ca/Gui/opensim/view/src/org/opensim/view/motions/MotionDisplayer.java#L825-L832

The `assemble()` was added to address #617.

@aymanhab would it make sense to fix this issue by detecting that the visualization is occurring during a forward simulation, and use that state directly?

The hacky fix would be to change the `assembly_accuracy` property in the Rajagopal model, but that does not fix this issue for other models, etc.

**Comment by chrisdembia** [comment]
@aymanhab could we use the following variable to determine if the states require assembly?

https://github.com/opensim-org/opensim-gui/blob/fa6407e08d0979285513842fbf08aca5b58e29ca/Gui/opensim/view/src/org/opensim/view/motions/MotionDisplayer.java#L408

**Comment by aseth1** [comment]
IMHO, the correct solution is to set the state on the model and not too interpret values from a Storage. If states are coming from a simulation then there is nothing to be done and rendering should be faster for it. If reading in files, then we need to convert values into states first. 

The current mechanism is convoluted. We compute valid states by running Tools, store their values in a Storage, or append them to a Storage to then give/associate with the Displayer. We then immediately require the Displayer to convert/reform the values in the Storage back into a valid state so we can render it.  Does this seem like a good process to anyone?

Secondarily, drawing forces and markers should be separate capabilities, e.g. `visualizeMarkers` and `visualizeForces` based on Tables of compatible data types. Then we can have control of what experimental data to any data source and avoid some of the issues in #912.

**Comment by aseth1** [comment]
Commenting out the assembly reduce the simulation time by about 50% in the model above. That's a good reason on its own to use a more direct display process.

**Comment by aymanhab** [comment]
@chrisdembia yes the line/variable you indicated tracks if motion is live (during a tool running not necessarily forward) vs. loaded from file. The motion displayer doesn't distinguish between tools.

Since @aseth1 suggested the assembly earlier for #617 fix and is suggesting removal now I have no objections.  

We sure should discuss improvements in the context of a long term plan that includes visualizing states and data but I wouldn't suggest that for current release cycle.

**Comment by aseth1** [comment]
Let me be clear. Assembly is required to fix #617. I am not suggesting to remove the assembly here. It cannot be removed as currently structured.  It is the structure of the MotionDisplayer that is forcing us to make workarounds that are inefficient.

**Comment by aymanhab** [comment]
I understand you're suggesting to keep this assemble call when playing back motion and to remove it when running FD. The follow up question, wouldn't that cause these same warning messages to appear when playing back FD results or running any other tools on FD results? Isn't the fundamental issue a descrepancy between  FD and assembly?

**Comment by chrisdembia** [comment]
Yes, it seems that the projection during integration does not require as tight of an accuracy. Maybe a default model assembly accuracy of `1e-9` is unreasonably tight.

**Comment by aseth1** [comment]
The problematic model *knee_patella_ligament* is included in `testAssemblySolver`. The issue there was being able to use the coordinate slider and draw the knee with the patella that was not in a weird place. The underlying problem was trying to balance the knee coordinate value (part of the assembly) the patella coordinate values (couple translations and rotations) and the fixed length of the constant distance constraint that was acting as the patella ligament. One fix was to crank the accuracy to make the constraint enforced more heavily, which works (renders the coordinate insignificant compared to the constraint error). An improvement (implemented later) was to allow constrained (dependent) coordinate to vary freely (`is_free_to_satisfy_constraints = true`) so the dependent coordinates values are not considered. 

I am able to pose this model with very low assembly accuracy now, and get reasonable results. Reasonable in the sense that the coordinate value might not be achieved but the patella constraint is not visibly violated. The tolerance was tightened because we could reach the coordinate values with tighter tolerances (0.1x tighter than accuracy).

For example, for the *knee_patella_ligament* models shown below, `assembly_accuracy = 1.0E-6` is in red and the `assembly_accuracy = 1.0E-9` in green when both models are set to -120degs for the knee_angle.

![image](https://user-images.githubusercontent.com/6494122/43558148-d5bcc75a-95bc-11e8-9ae1-7c7a9ab7323a.png)

You can see that the tighter model (green) reaches -119.993, which is pretty darn close to -120degs while the looser model (red) only achieves -114.878degs. Note also that the goals are assessed in radians. IIRC  Matt did not like this discrepancy, and I think that is how we settled on 1e-9 (which triggers error below).

```
Model unable to assemble: AssemblySolver::assemble() Failed: SimTK Exception thrown at assembler.cpp:897:
  Method Assembler::assemble() failed because:
Unable to achieve required assembly error tolerance.
Assembly error tolerance achieved: 3.9137794394239478e-10 required: 1e-10.
Model relaxing constraints and trying again.
```

**Comment by aseth1** [comment]
Looking at it closely again, the model complains only when the angle is at the extremes of its range of motion and this correspond to the ends of the splines that are only specified between (-120.000280612, 10.0000042858) in which case the splines and their derivatives could be poorly defined. I believe this is the same situation with Apoorvas' model. We should have @apoorvar explore:
1. whether assembly errors only happen at the ends of the range of motion of the knee and then,
2. if extending these splines so they are well-defined at end points eliminates the problem.

**Comment by aseth1** [comment]
> The follow up question, wouldn't that cause these same warning messages to appear when playing back FD results or running any other tools on FD results? Isn't the fundamental issue a descrepancy between FD and assembly?

@aymanhab These are two fundamentally different operations. A FD simulation is satsifying a set of DAE where projection is used to satisfy algebraic equations imposed on evolving states. Assembly is finding a pose that satisfies constraints and minimizes goals (distance from target joint angle, for example) in a least-squares sense.  We cannot expect these operations to provide the same answer, in general. Yes, if we relax tolerances and have a lot of slop we might get away without noticing or worse having more and visible discrepancies between simulated and posed models. 

The assembly, in my view, is a hammer to get a model to conform when you don't have simulation data. If you have a simulation and have to still assemble it then there is something wrong in our workflow/process. Doing an assembly at the point of display is the worst of all cases since the assembly performance costs are always imposed. IMHO, we should only be doing assembly to initialize the model and a simulation.

**Comment by chrisdembia** [comment]
@aseth1 @aymanhab and I looked into this further. The issue is not related to the `Rajagopal2015.osim` model. Rather, the issue is that the visualization enforces clamps, even for motions that were generated without the clamps (e.g., forward simulation). The same assembly accuracy warnings can be generated with `bouncing_block.osim`.

We need to revisit the changes in https://github.com/opensim-org/opensim-gui/pull/608/files and detect whether a motion/state is complete and therefore not call `assemble()`, or if the motion is incomplete and we must call `assemble()`. The best place to make this determination is in `Model::formStateStorage()`.

@aseth1 @aymanhab please correct any errors, or add anything I missed.

**Comment by aymanhab** [comment]
Great summary @chrisdembia 
Since we agreed on the work (deciding if read file sto/mot corresponds to a full state or not) needs to be done in formStateStorage, we can 
- have the method return a boolean (instead of void)  indicating if passed in Storage has full state or not (@chrisdembia or @aseth1)
- modify MotionDisplayer on GUI side to utilize the flag and not assemble in case  dealing with full state( Ayman)

Thoughts?

**Comment by aseth1** [comment]
I agree `formStateStorage` is a good place to do the check. I am happy to consider it. Ideally we would streamline further to enable the translation from file to a `StatesTrajectory` (perhaps in 4.1) and the animation would be a strict/fast operation of rendering the `State` of a model.

**Comment by chrisdembia** [comment]
@aymanhab, the method `Model::formStateStorage()` takes a flag `warnUnspecifiedStates` that is true by default. In this code below, we don't see any warnings even when playing a MOT file (IK solution for arm26). Do you know why?

https://github.com/opensim-org/opensim-gui/blob/33dbb78dae397cfbf99e9368c67c2fffbbdbc05c/Gui/opensim/view/src/org/opensim/view/motions/MotionDisplayer.java#L441-L450

**Comment by chrisdembia** [comment]
@aymanhab nevermind; we were looking at an older commit.

**Comment by aseth1** [comment]
It turns out for #617 the underlying cause was not missing values but incorrectly interpreted values. In 3.3 the  `knee_angle_pat_r` Coordinate was user-specified as being Rotational and thus was being converted to degrees when written the IK.mot file. Unfortunately, that assertion is wrong because the spatial rotation is some nonlinear (Spline) function of the `knee_angle_pat_r` and 4.0 does not interpet the values in degrees requiring conversion back to radians, so the values in degrees are being applied.  The assembly was a band-aid that corrected for that misinterpretation.

**Comment by chrisdembia** [comment]
@aymanhab our current plan was to generate a warning in `Coordinate::updateFromXML()` if we notice that if a non-rotational coordinate (e.g., 'knee_angle_pat_r`) was marked as rotational in an old XML file; this is the situation that causes a data column like `knee_angle_pat_r` to be treated as radians when it's actually in degrees. What do you think?

**Comment by aymanhab** [comment]
That sounds great @chrisdembia, wouldn't old result files (mot, sto) be problematic as well? if so we should include that in the warning and release notes.

**Comment by chrisdembia** [comment]
👍
