### ISSUE TITLE
Movie/video maker does not respect playback speed

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#895]
Jen: Users expect to be able to make beautiful movies to illustrate their simulations. Being able to change playback speed is a key part of this.

### Steps to reproduce
1. Load the drop landing model from [here](https://stanford.box.com/s/3ifyk4w9py6lbxltq75jxx62c4n72ae7) 
2. load the original states file: [incline_30.0_gain_10.0_delay_0.06_states .sto.txt](https://github.com/opensim-org/opensim-gui/files/2203714/incline_30.0_gain_10.0_delay_0.06_states.sto.txt)
3. The total landing motion is only 0.15s, so set the playback speed to 0.1 to animate in slow motion.
4. click movie camera icon to start recording, press play and then click camera to stop recording.

### Expected result
Resulting video is 1.5s in duration with some 45-90 time frames (30-60Hz).

### Actual result
The resulting video lasts only 0.02s and contains 3 time frames.

### Environment and GUI version
Windows OpenSim_b435c8fa-2018-07-06

**Comment by aymanhab** [comment]
Some notes:
1. the motion associated with the model is actually 15 seconds rather than 0.15 seconds . Since we try to play motion real time by default, using very small time is fundamentally error prone (how soon did you push the buttons to start/stop etc. what's the startup time to initialize the capture etc.).
Using the 15 sec motion out of the box produces videos of length:
 - normal speed: 15 sec.
 - half speed: 26 sec.
 - tenth of speed: 2 min 2 sec.

2. I did tweak some parameters on the capture, and was able to get 15, 30, 2:28 so I can make a build with this change.

Not sure how you counted frames in webm to tell there're 3 frames but would be good to know so we're in sync.

-

**Comment by aseth1** [comment]
> the motion associated with the model is actually 15 seconds rather than 0.15 seconds .

I manually lengthened the time from 0.15s to 15s so I could produce a reasonable video. I believe I submitted the original file that was not stretched out. I just downloaded and it is 0.15s, so I don't know how you got the 15s file. There is no way the drop landing is naturally 15s.

I counted 3 frame by playing by sliding the MP4 player slider and saw it tansition between three frames.

**Comment by aymanhab** [comment]
@aseth1 The zip file available from the link you posted at the top of this issue has only one sto file that has "time_stretched" in the name and indeed it is 15 seconds. Where do I get the non time stretched version?

**Comment by aseth1** [comment]
Yes, but please read step 2!

**Comment by aseth1** [comment]
Retested with OpenSim_11d7a130-2018-08-03 on Windows and at a playback speed of 0.05 produced a video of 5s some 2s of which was time to press play and press the camera icon to stop, so give our take 3s, which seems right. At a speed of 0.1s (motion alone should take 1.5s) the total time was ~3s which includes user time to press play and stop the recording.

I consider the issue verified on Windows, but we should have another issue that recording should only occur while their is motion. Most of the collection time in these short motions is idle time.

**Comment by jenhicks** [comment]
I tested on Mac and see same behavior. I agree about making another issue ... @aseth1  have you done this already?
