### ISSUE TITLE
Crashes occur while changing a Joint's sockets for parent/child frame

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#994]
### Steps to reproduce
**Case 1**
1. Open arm26.osim
2. Navigate to r_shoulder
3. Change PhysicalFrame:parent_frame to r_ulna_radius_hand (then click in visualizer window to accept)
4. Hit OK for all error messages.
5. Change PhysicalFrame:parent_frame to any other frame (e.g., ground) (then click in visualizer window to accept)
6. See crash log below

[hs_err_pid18932.log](https://github.com/opensim-org/opensim-gui/files/2367792/hs_err_pid18932.log)

**Case 2**
1. Open arm.26
2. Navigate to r_shoulder
3. Change PhysicalFrame:child_frame to ground (then click in visualizer window to accept)
4. See crash log below

[hs_err_pid4140.log](https://github.com/opensim-org/opensim-gui/files/2367818/hs_err_pid4140.log)

### Environment and GUI version
W10 OpenSim 4.0-2018-09-04-a2736979

**Comment by aymanhab** [comment]
Possible solutions that don't require significant API change/work:

1. Disable editing Frames specifically for Joints (this is unintended new functionality anyway)
2. Disable creating invalid Trees by filtering out upstream Frames.
3. Introduce API methods to call/check before making destructive changes.

Any other suggestions/ideas? 
Other than option 1, we'll need to write custom code to handle Joint-Frame edits different from the generic off-the-shelf connection edit code.

**Comment by aseth1** [comment]
I believe this is the same/related issues as #529 and #587.

**Comment by aseth1** [comment]
> 1. Disable editing Frames specifically for Joints (this is unintended new functionality anyway)

I disagree with it being unintended functionality. In fact the point of introducing Connectors back in 2014 was to facilitate some form of model editing/building beyond property editing.

> 2. Disable creating invalid Trees by filtering out upstream Frames.

If we knew for sure what would lead to an invalid tree we would make  `MultibodyGraphMaker` more robust to begin with. 

>3. Introduce API methods to call/check before making destructive changes.

The API does not claim to provide a valid tree and does not return an invalid model. It throws an Exception. It seems more straightforward to cache the model before a topological change, make the change, if no errors continue on with the new model, otherwise reset to the cached model and present the user with the message. That is essentially what we were trying to establish for #587.

The issue from the API side is if you are not getting an Exception with a reasonable message. Is that the case?

**Comment by carmichaelong** [comment]
Another related but more tangential issue is #850. This makes editing a Joint's socket more error prone.

**Comment by aymanhab** [comment]
@aseth1 I did more investigation into this, and I suspect the issue is that 
MultibodyGraphMaker::bodies is not cleared on subsequent calls to initSystem(), causing the model to be in "limbo" state and initSystem to fail. Can you clarify when is this supposed to be cleared/created so I can dig a bit deeper? Thanks

**Comment by aseth1** [comment]
Thanks @aymanhab I'll look into this.

**Comment by aseth1** [comment]
@aymanhab if you were initializing an object by calling an initialization routine and it threw an exception, during that process would you continue to use that object as if nothing happened? What guarantees would you have that its internals were even defined at all? This is what is happening in your test context examples. You are asking the model to initialize internal members (system and state) and in the midst of doing that it throws. Why would you think that the model's internals are still usable? The simplest and safest action is to throw away that model. We have no idea what intermediate/slave bodies, constraints, free joints, might be added (in full or some partial form) to the model when the exception is thrown. This is the lingering bodies one can see in the model, and is not an issue of  graph maker. The graph is being correctly cleared, but the model itself is corrupted.

As far as I can see it, we can make an already model construction process even more complicated by trying to figure out how to unwind topological changes to the model, but I think it is a lot easier, simpler and safer to just throw away the model!  I think it is pretty standard procedure  to clear the object you are trying to modify in a try block upon catching the exception.

For example would you do this?
```cpp
Object a;
try {
   a.addThis();
   a.addThat();
   a.init();
}
catch (...) {
   a.removeThis();
   a.removeThat();
   a.init();
}
```
Who would ever expect this to work in general? Opposed to the straightforward and safer approach of assuming that `a` is garbage and restoring it.
```cpp
Object a;
Object cachedA{a};
try {
   a.addThis();
   a.addThat();
   a.init();
}
catch (...) {
    //whoops we mangled a, so restore it
   a = cachedA;
}
```

The logic of the `OpenSimContext`  is confusing to me since the `restore...` method names sound like they should be doing this.  `OpenSimContext` even maintains a `clonedModel` reference but calls `initSystem` on the clone when ever you ask it to `restoreStateFromCachedModel`, which doesn't seem right. I would rename `clonedModel` to `_cachedModel` to be consistent with member and function naming. Then, do not re-initSystem() on the `_cachedModel` but hang on to it live. Then when an` Exception` occurs during editing of the model, reset the current model to the `_cachedModel`.

**Comment by aymanhab** [comment]
@aseth1 Thanks for the investigation. Things that you need to keep in mind:
1. Model is used by the GUI and can't be thrown away as any non-toy API program would do. Practically there're references to the model in other places, we can't just throw it away!
2. Assigning values from cachedModel (which I tried by the way) doesn't help either since it just copies properties, restoring the value of the one old property that was changed does the exact same thing.
3. There's no assumption made about the State or System of the model in hand other than that we can call initSystem on it which is exactly what we do. I don't think the heavier 🔨 of throw away is acceptable  but if there's one bigger than initSystem please let me know.
4. I agree some of the names and flow is a bit confusing if you're not in the actual GUI code base but that has no bearing on the issue AFAIK. Sorry about the confusion. I can reproduce this with just straight call to the model if that helps.

**Comment by aseth1** [comment]
> Assigning values from cachedModel (which I tried by the way) doesn't help either since it just copies properties, restoring the value of the one old property that was changed does the exact same thing.

This is not correct. This assumes that only one property or internal member was affected. You do not know what has to happen internally to build a valid topology. Yes connectToModel does change the model. Reverting to the previous will work. I tried it.

**Comment by aymanhab** [comment]
If by reverting you mean assign the values using the = operator, then please update the test case and it will pass and we're done. Thank you!

**Comment by aseth1** [comment]
It will work. Test only fails because you are holding onto to sockets and other internals that are on old model. Why would expect these to persist if the model is reverted?

**Comment by aymanhab** [comment]
So, let me clarify, the sockets are created anew when initSystem is called so we shouldn't hold on to a reference to a socket?

**Comment by aseth1** [comment]
A socket belongs to a Component. The socket will persist as long as the Component does.

**Comment by aseth1** [comment]
The is non persistence issue a consequence of the operation: Set A = Set B.  Set A does not point to the objects in B, they are cloned. So the shoulder reference in your test case is now "dead" even if I use the = operator. If you get a reference to the component or its socket in A, you are fine.

**Comment by aymanhab** [comment]
That was informative @aseth1 👍  Thank you. I'll look into it again with your comments in mind. I'm not sure how we documented that users shouldn't hold on to a State across initSystems in the past but it seems API users (including the GUI) should be aware of more of these objects. It would be great if that's documented somewhere.

**Comment by aymanhab** [comment]
@carmichaelong when we have a build please feel free to check all edits to joints, possibly using the model building utilities and related issues linnked above. Would also be good to keep track if error messages make sense. Thank you 💯

**Comment by carmichaelong** [comment]
W10 Pro with OpenSim 4.0-2018-10-12-3071a2d5:

I used arm26 and tried many combinations of `child_frame` and `parent_frame` for the three Joints using the Sockets pull-down menu. In all cases, either the model respected the change or an exception was thrown, and the GUI did not crash. I opened other issues that were observed during testing, but I think this issue and other linked issues have been addressed as they are related to crashing.
